# Generated by Django 5.0.1 on 2025-05-29 14:22

import django.db.models.deletion
import django.utils.timezone
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузовов',
            },
        ),
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('special_requirements', models.TextField(blank=True, default='', verbose_name='Особые требования')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы грузов',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Промокод')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Процент скидки')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(default=main.models.get_default_end_date, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('max_uses', models.PositiveIntegerField(blank=True, default=100, null=True, verbose_name='Макс. использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
            ],
            options={
                'verbose_name': 'Акция',
                'verbose_name_plural': 'Акции',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('base_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Базовая цена')),
                ('max_weight', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Максимальный вес (кг)')),
                ('max_volume', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Максимальный объем (м³)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип транспорта',
                'verbose_name_plural': 'Типы транспорта',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+375', max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(default='', max_length=500, verbose_name='Адрес')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Название компании')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+375', max_length=20, verbose_name='Телефон')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Опыт (лет)')),
                ('categories', models.CharField(default='B', max_length=50, verbose_name='Категории прав')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='drivers/', verbose_name='Фото')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[main.models.validate_driver_age], verbose_name='Дата рождения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(default='', max_length=500, verbose_name='Адрес загрузки')),
                ('delivery_address', models.CharField(default='', max_length=500, verbose_name='Адрес доставки')),
                ('weight', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, verbose_name='Вес (кг)')),
                ('volume', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, verbose_name='Объем (м³)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В процессе'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Итоговая цена')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('cargo_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cargotype', verbose_name='Тип груза')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.client', verbose_name='Клиент')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.driver', verbose_name='Водитель')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Не указано', max_length=200, verbose_name='Марка')),
                ('model', models.CharField(default='Не указано', max_length=200, verbose_name='Модель')),
                ('year', models.PositiveIntegerField(default=2024, verbose_name='Год выпуска')),
                ('plate_number', models.CharField(default='Не указано', max_length=20, verbose_name='Гос. номер')),
                ('capacity', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='Грузоподъемность (кг)')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Изображение')),
                ('body_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.bodytype', verbose_name='Тип кузова')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.vehicletype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.vehicle', verbose_name='Транспортное средство'),
        ),
        migrations.AddField(
            model_name='service',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.vehicletype', verbose_name='Тип транспорта'),
        ),
    ]
