# Generated by Django 5.0.1 on 2025-09-21 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_banner_companyhistory_companyinfo_dictionary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='company/videos/', verbose_name='Видео файл'),
        ),
    ]
